:hivemq-link: http://www.hivemq.com
:influxdb-github-link: https://github.com/influxdata/influxdb
:hivemq-support: http://www.hivemq.com/support/
:docker: https://www.docker.com/
:kitematic: https://kitematic.com/
:influx-docker: https://hub.docker.com/_/influxdb/


== InfluxDB Monitoring Plugin for HiveMQ 4

=== Purpose

The InfluxDB Monitoring plugin allows {hivemq-link}[HiveMQ 4] to connect to an instance of {influxdb-github-link}[InfluxDB] for time series monitoring.

=== Installation InfluxDB Monitoring Plugin
Installing the plugin for HiveMQ 4 is very easy:

. Copy the folder `hivemq4-influxdb-monitoring-plugin` to your `[HIVEMQ_HOME]/plugins` folder
. In the plugin folder, modify the `influxdb.properties` file to fit your needs, check that the mandatory properties are set
. Remove (or rename) the `DISABLED` file in the plugin folder to enable the InfluxDB plugin
. Done

=== Quick Start InfluxDB
If you don't already have an InfluxDB instance set up, here is a instruction how to start an basic InfluxDB instance with Docker.

. Download and install {docker}[Docker] for your platform
. Start an InfluxDB container with the command `docker run -p 8086:8086 -v $PWD:/var/lib/influxdb influxdb`. For more information about using InfluxDB with Docker visit the {influx-docker}[official Docker repository] for InfluxDB
. Create a database that matches the name set in the property `database` in `influxdb.properties`. For the default `database` value use the command `curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE hivemq"`
. Done

=== Usage
After the plugin is installed and an InfluxDB instance exists.

. If not already done, enable the plugin (remove or rename the `DISABLED` file)
. Start HiveMQ 4
. Plugin successfully started if configuration file exists and contains required properties

=== Configuration
The InfluxDB Monitoring plugin uses its own configuration file `influxdb.properties`. The plugin won't start if this file is missing or the required properties are not set.

==== General Configuration

|===
| Config name | Required | Description | Default

| mode | no | The mode configured for the InfluxDB sender. Possibilities are: http, tcp, udp | http
| host | yes | The host name of the InfluxDB instance. | -
| port | yes | The port number the InfluxDB instance is listening. | -
| protocol | no | The protocol the InfluxDB sender uses in http mode. | http
| auth | no | The authorization string to be used to connect to InfluxDB, of format username:password. | -
| prefix | no | The measurement prefix. | -
| database | no | The database name. | hivemq
| reportingInterval | no | The reporting interval in seconds. | 1
| connectTimeout | no | The connect and read timeout in seconds. | 5000
| tags | no | The tags for each metric. Listed as a semicolon ( `;` ) separated list. | -

|===


.Example Configuration
[source]
----
mode:http
host:localhost
port:8086
protocol:http
auth:

prefix:
database:hivemq

reportingInterval:1
connectTimeout:5000

tags:host=hivemq1
----

=== Need help?

If you encounter any problems, we are happy to help. The best place to get in contact is our {hivemq-support}[support].