mode:cloud
host:localhost
port:8086
protocol:http
auth:my3Iy5aMxCGeD-jrzrlhXnYyII0UMFPtsE98c6LaV-VMgG08WGMK2aoFxLV9-PMJ_daBiZy3yz0IGCXl07ppOw==

prefix:
database:hivemq

reportingInterval:1
connectTimeout:5000

tags:host=localhost

# InfluxDB cloud options
bucket:hivemq
organization:hivemq